name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]  # Only amd64 platform is listed here
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Determine architecture
      run: echo "ARCH=$(echo ${{ matrix.platform }} | cut -d/ -f2)" >> $GITHUB_ENV

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: manfromdownunder/docker-minecraft-craft-to-exile-2:0.5.2b, manfromdownunder/docker-minecraft-craft-to-exile-2:latest, manfromdownunder/docker-minecraft-craft-to-exile-2:${{ github.sha }}
        platforms: ${{ matrix.platform }}
        build-args: ARCH=${{ env.ARCH }}

#    - name: Build and push Docker image to GitHub Container Registry
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: ghcr.io/${{ github.repository_owner }}/docker-minecraft-craft-to-exile-2:1.19.2, ghcr.io/${{ github.repository_owner }}/docker-minecraft-craft-to-exile-2, ghcr.io/${{ github.repository_owner }}/docker-minecraft-craft-to-exile-2:${{ github.sha }}
#        platforms: ${{ matrix.platform }}
#        build-args: ARCH=${{ env.ARCH }}